// Generated by scripts/export-abi.mjs from contracts/out/AgentHireEscrow.sol. Do not edit.
export const agentHireEscrowAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "facts_",
        "type": "address",
        "internalType": "contract IAgentFacts"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "FACTS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAgentFacts"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hire",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct AgentHireEscrow.Params",
        "components": [
          {
            "name": "minAge",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "minDepth",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "k",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "c",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "baseBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minAttestors",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxStaleness",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "deadline",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "jobId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "jobCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "jobOf",
    "inputs": [
      {
        "name": "jobId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AgentHireEscrow.Job",
        "components": [
          {
            "name": "hirer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "payee",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "chainKey",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "premiumBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "closed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "held",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quote",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct AgentHireEscrow.Params",
        "components": [
          {
            "name": "minAge",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "minDepth",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "k",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "c",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "baseBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minAttestors",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "maxStaleness",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "riskBps",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "premiumBps",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "f",
        "type": "tuple",
        "internalType": "struct IAgentFacts.Facts",
        "components": [
          {
            "name": "breadthRaw",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "breadthGrounded",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "breadthIndependent",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapCount",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "negatives",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "cloneDensityLB",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "registrantSiblings",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "uriSiblings",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sameTxSiblings",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "firstRegisteredHeight",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "coveredThrough",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "minAttestors",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "truncated",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "staleness",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "refund",
    "inputs": [
      {
        "name": "jobId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "release",
    "inputs": [
      {
        "name": "jobId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Hired",
    "inputs": [
      {
        "name": "jobId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "chainKey",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "payee",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "premiumBps",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "premium",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "held",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Refunded",
    "inputs": [
      {
        "name": "jobId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Released",
    "inputs": [
      {
        "name": "jobId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadDeadline",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Closed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Gated",
    "inputs": [
      {
        "name": "gapCount",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotHirer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Stale",
    "inputs": [
      {
        "name": "lag",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "max",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "ThinQuorum",
    "inputs": [
      {
        "name": "have",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "want",
        "type": "uint32",
        "internalType": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "TooEarly",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Truncated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownAgent",
    "inputs": []
  }
] as const;
