// Generated by scripts/export-abi.mjs from contracts/out/CoverageBounty.sol. Do not edit.
export const coverageBountyAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "facts_",
        "type": "address",
        "internalType": "contract GroundedFacts"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "FACTS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract GroundedFacts"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bountyCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bountyOf",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct CoverageBounty.Bounty",
        "components": [
          {
            "name": "funder",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "chainKey",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "minAge",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "minDepth",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "k",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "c",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiry",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "closed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "decision",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "decisionOf",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minAge",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "minDepth",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "k",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "c",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "fund",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minAge",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "minDepth",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "k",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "c",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "proveAndClaim",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "proofs",
        "type": "tuple[]",
        "internalType": "struct GroundedFacts.Proof[]",
        "components": [
          {
            "name": "chainKey",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "height",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "encodedTx",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "merkleProof",
            "type": "tuple",
            "internalType": "struct INativeQueryVerifier.MerkleProof",
            "components": [
              {
                "name": "root",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "siblings",
                "type": "tuple[]",
                "internalType": "struct INativeQueryVerifier.MerkleProofEntry[]",
                "components": [
                  {
                    "name": "hash",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  },
                  {
                    "name": "isLeft",
                    "type": "bool",
                    "internalType": "bool"
                  }
                ]
              }
            ]
          },
          {
            "name": "continuityProof",
            "type": "tuple",
            "internalType": "struct INativeQueryVerifier.ContinuityProof",
            "components": [
              {
                "name": "lowerEndpointDigest",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "roots",
                "type": "bytes32[]",
                "internalType": "bytes32[]"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Claimed",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "claimant",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "newDecision",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Funded",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "chainKey",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "decision",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadExpiry",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Closed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Expired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoChange",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotFunder",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooEarly",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  }
] as const;
