// Generated by scripts/export-abi.mjs from contracts/out/GroundedFacts.sol. Do not edit.
export const groundedFactsAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "registries",
        "type": "tuple[]",
        "internalType": "struct GroundedFacts.Registry[]",
        "components": [
          {
            "name": "chainKey",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "identity",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "reputation",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "BUCKET",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_REVIEWERS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "admittedTx",
    "inputs": [
      {
        "name": "txKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "agentOf",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct GroundedFacts.Agent",
        "components": [
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "registrant",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "uriHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "txKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "registeredHeight",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastOwnerUpdate",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "transfersProven",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "attestedTip",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "chainKeys",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64[]",
        "internalType": "uint64[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "clientsOf",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "facts",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minAge",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "minDepth",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "f",
        "type": "tuple",
        "internalType": "struct IAgentFacts.Facts",
        "components": [
          {
            "name": "breadthRaw",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "breadthGrounded",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "breadthIndependent",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gapCount",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "negatives",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "cloneDensityLB",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "registrantSiblings",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "uriSiblings",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sameTxSiblings",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "firstRegisteredHeight",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "coveredThrough",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "minAttestors",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "truncated",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isRegistered",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ownerOf",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pairOf",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "client",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct GroundedFacts.Pair",
        "components": [
          {
            "name": "maxIndex",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "known",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "active",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "firstHeight",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "listed",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "record",
    "inputs": [
      {
        "name": "proofs",
        "type": "tuple[]",
        "internalType": "struct GroundedFacts.Proof[]",
        "components": [
          {
            "name": "chainKey",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "height",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "encodedTx",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "merkleProof",
            "type": "tuple",
            "internalType": "struct INativeQueryVerifier.MerkleProof",
            "components": [
              {
                "name": "root",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "siblings",
                "type": "tuple[]",
                "internalType": "struct INativeQueryVerifier.MerkleProofEntry[]",
                "components": [
                  {
                    "name": "hash",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  },
                  {
                    "name": "isLeft",
                    "type": "bool",
                    "internalType": "bool"
                  }
                ]
              }
            ]
          },
          {
            "name": "continuityProof",
            "type": "tuple",
            "internalType": "struct INativeQueryVerifier.ContinuityProof",
            "components": [
              {
                "name": "lowerEndpointDigest",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "roots",
                "type": "bytes32[]",
                "internalType": "bytes32[]"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "admitted",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "registryOf",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct GroundedFacts.Registry",
        "components": [
          {
            "name": "chainKey",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "identity",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "reputation",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "reviewerOwnsAgents",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "reviewerSeniority",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "reviewer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct GroundedFacts.Activity",
        "components": [
          {
            "name": "oldest",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "buckets",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AgentProven",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "registrant",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnerUpdated",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReviewProven",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "client",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "feedbackIndex",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "value",
        "type": "int128",
        "indexed": false,
        "internalType": "int128"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReviewRevoked",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "client",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "feedbackIndex",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TxAdmitted",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "height",
        "type": "uint64",
        "indexed": true,
        "internalType": "uint64"
      },
      {
        "name": "txIndex",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "from",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "attestors",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadRegistry",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProofRejected",
    "inputs": [
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownChain",
    "inputs": [
      {
        "name": "chainKey",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  }
] as const;
