// Export contract ABIs from contracts/out into packages/core/src/abi/*.ts (typed `as const`).
// Run after `forge build`. The core package build fails if an ABI it imports is missing.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const names = { GroundedFacts: "groundedFactsAbi", AgentHireEscrow: "agentHireEscrowAbi", CoverageBounty: "coverageBountyAbi" };
for (const [contract, exportName] of Object.entries(names)) {
  const out = JSON.parse(readFileSync(join(root, "contracts/out", `${contract}.sol`, `${contract}.json`), "utf8"));
  const body = `// Generated by scripts/export-abi.mjs from contracts/out/${contract}.sol. Do not edit.\nexport const ${exportName} = ${JSON.stringify(out.abi, null, 2)} as const;\n`;
  writeFileSync(join(root, "packages/core/src/abi", `${contract}.ts`), body);
  console.log(`abi: ${contract} (${out.abi.length} entries)`);
}
